# Site settings
title: The Corner Datastore
email: smartperson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Varun's blog. A place for blogging with blogs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://varunmehta.com" # the base hostname & protocol for your site
twitter_username: smartperson
github_username:  smartperson
# google_play: 'GDGX'
# google_plus_com: '109485346959707049693'  # Community link
# google_plus_per: '+GDGManagua'  #Personal link
# facebook_app_id: 12345
search_enabled: false

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

#more_vert:
#  - name: Cool Option 1
#    link: www.myawesomelink.com
#  - name: Cool Option 2
#    link: www.myawesomelink.com
#  - name: Cool Option 3
#    link: www.myawesomelink.com

disqus: false
disqus_shortname: ''

# Build settings
markdown: kramdown

cloudinary:
  cloud_name: varun-blog
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90"
    onethird:
      min_width: 110
      max_width: 535
      fallback_max_width: 300
      steps: 3
      sizes: "(min-width: 50rem) 17rem, 30vw"
      attributes:
        class: "one3rd"

gems:
  - jekyll-cloudinary