# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Disqovery Blog
email: varun@disqovery.com
description: > # this means to ignore newlines until "baseurl:"
  The blog for Disqovery: the app that takes care of employee feedback and analytics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.disqovery.com" # the base hostname & protocol for your site
twitter_username: disqovery
github_username:  smartperson

# Build settings
markdown: kramdown
gems: ['jekyll-twitter-plugin']

twitter:
  consumer_key: dkor8YimCdch8aWZlkydBQ
  consumer_secret: aGUBsmiTh1d0ATcQYbHj5nhiJKElXJuSsmUwlN0
  access_token: 19297331-nrXFkPbQuxkpcnxAV9FJUMzD6Uw1NxRX0ycAN3NI
  access_token_secret: 62XxGA1maOjFPxewHGi4QfNALcTSsvkGLz860vIKC5E