# Site settings
title: The Corner Datastore
email: me@varunmehta.com
description: > # this means to ignore newlines until "baseurl:"
  Varun's blog. A place for blogging with blogs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://varunmehta.com" # the base hostname & protocol for your site
github_username:  smartperson
mastodon_url: https://fosstodon.org/@smartperson
mastodon_username: smartperson
search_enabled: false

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: false
disqus_shortname: ''

# Build settings
markdown: kramdown

cloudinary:
  cloud_name: varun-blog
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90"
    onethird:
      min_width: 110
      max_width: 535
      fallback_max_width: 300
      steps: 3
      sizes: "(min-width: 50rem) 17rem, 30vw"
      attributes:
        class: "one3rd"

gems:
  - jekyll-cloudinary